# RegEx FULL FORM IS REGULAR EXPTRESSIONS . 

# REGULAR EXPRESSIONS IS A SEQUENCE OF CHARACTERS THAT FORMS A SEARCH PATTERN .

# THE MODULE OF REGULAR EXPTRESSIONS IS DENOTED BY "re" .

# GET THE dir OF re MODULE . 

import re
print ( dir(re) )

'''

THE LIST OF METACHARACTERS .

\ -- ESCAPE CHARACTERS 
. -- ANY CHARACTERS EXCEPT IN NEW LINE CHARACTER 
^ -- STARTS WITH
$ -- ENDS WITH
* -- ZERO OR MORE CHARACTERS 
+ -- ONE OR MORE CHARACTERS 
? -- ZERO OR ONE CHARACTER
{} -- EXACTLY SPECIFIED NUMBER OF CHARACTERS 
| -- EITHER OR 
() -- CAPTURE GROUP

'''

# THE findall FUNCTION .

# EXAMPLE ONE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
a = re.findall ( "IS" , txt )
print(a)

# EXAMPLE TWO

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
b = re.findall ( " I" , txt )
print(b)

# EXAMPLE THREE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
c = re.findall ( " " , txt )
print(c)

# IF IN findall THE CONDITION IS NOT FULLFILLED THEN IT WILL RETURN EMPTY LIST .

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
d = re.findall ( "FOR" , txt )
print(d)

# THE search FUNCTION .

# EXAMPLE ONE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
e = re.search ( "^HELLO.*ISTANBUL$" , txt )

if e:
    print ( "YES MATCH IS TRUE" )
else:
    print ( "NO MATCH IS FALSE" )

# EXAMPLE TWO   

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
f = re.search ( "^HELLO.?ISTANBUL$" , txt )

if f:
    print ( "YES MATCH IS TRUE" )
else:
    print ( "NO MATCH IS FALSE" )    

# EXAMPLE THREE  

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
g = re.search ( "\s" , txt )
print ( "THE FIRST WHITE SPACE IS LOCATED AT" , g.start() )

# IF IN search NOTHING IS FOUND THEN IT WILL RETURN "None" .

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
h = re.search ( "ALAN" , txt )
print(h)

# THE split FUNCTION .

# EXAMPLE ONE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
k = re.split ( " " , txt )
print(k)

# EXAMPLE TWO  

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
m = re.split ( "MY" , txt )
print(m)

# EXAMPLE THREE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
n = re.split ( "\s" , txt )
print(n)

# TO CONTROL THE NUMBER OF SPLIT OCCURANCE SPECIFIY THE NUMBER OF MAXIMUM SPLIT PARAMETER .

# EXAMPLE ONE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
p = re.split ( "\s" , txt , 7 )
print(p)

# EXAMPLE TWO  

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
q = re.split ( "\s" , txt , 14 )
print(q)

# EXAMPLE THREE 

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
r = re.split ( "\s" , txt , 21 )
print(r)

# THE sub FUNCTION .

# sub FUNCTION REPLACES THE GROUP OF ONE OR MORE CHARACTERS WITH ANOTHER GROUP OF ONE OR MORE CHARACTERS .

# EXAMPLE ONE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
s = re.sub ( " " , "_" , txt )
print(s)

# EXAMPLE TWO 

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
t = re.sub ( "\s" , "_" , txt )
print(t)

# EXAMPLE THREE 

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
u = re.sub ( " " , " # " , txt )
print(u)

# EXAMPLE FOUR

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
v = re.sub ( "EIGHT" , "FOUR" , txt )
print(v)

# TO CONTROL THE NUMBER OF REPLACEMENT OCCURANCE SPECIFIY THE NUMBER OF COUNT REPLACEMENT PARAMETER .

# EXAMPLE ONE

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
w = re.sub ( " " , "_" , txt , 6 )
print(w)

# EXAMPLE TWO

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
x = re.sub ( " " , "_" , txt , 13 )
print(x)

# EXAMPLE THREE 

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
y = re.sub ( " " , "_" , txt , 23 )
print(y)

# EXAMPLE FOUR

import re
txt = "HELLO MY FULL NAME IS TOM CRUISE AND MY AGE IS FOURTY EIGHT YEARS AND MY HOME TOWN IS ISTANBUL"
z = re.sub ( "\s" , " # " , txt , 40 )
print(z)